Add log files to gitignore [clean up]
facebookresearch/fastMRI pull request #103
Opened 2020-11-08 01:13 UTC by kapoor1992

The lightning log files are generated and not required in the repo so it might be best to disregard them from version control.

2020-11-08 02:10 UTC, mmuckley requested changes

2020-11-08 02:10 UTC, mmuckley commented on .gitignore
> +lightning_logs/
Just add a newline here.

2020-11-10 01:07 UTC, kapoor1992 commented on .gitignore
> +lightning_logs/
Added!

2020-11-10 01:40 UTC, mmuckley approved these changes
LGTM

2020-11-10 01:40 UTC, merged