Subsample dataset by volume fix
facebookresearch/fastMRI pull request #122
Opened 2021-02-13 01:20 UTC by z-fabian

If `sample_rate < 1.0`, `SliceDataset` subsamples the training dataset by slices and not by volumes. This is undesired since 
1. Based on the function documentation says `sample_rate` should control what fraction of the volumes should be loaded. 
2. Subsampling by volumes makes more sense in practice. Randomly selected slices can create very unbalanced datasets (possibly lots of empty slices) and subsampling by volumes mimics the real life case of having less MRI volumes for training.  

This fix modifies `SliceDataset` to subsample by volumes when `sample_rate < 1.0`. If subsampling by slice is the desired behavior, then we should update the fuction helper to reflect that.

2021-02-16 22:03 UTC, mmuckley requested changes
My worry here is we're breaking backwards compatibility. If someone has a project that depends on the repository and they want to reproduce an old result, this may break their code. Instead I would recommend a new variable, such as `volume_sample_rate`, and make sure that `sample_rate` and `volume_sample_rate` aren't set simultaneously, throwing an exception if they are. This might be best if both defaulted to `None` rather than `1.0`, but that's open to the implementation as you wish..

2021-02-17 22:09 UTC, z-fabian commented
@mmuckley As you suggested I added a new argument `volume_sample_rate`. If it is not set, `sample_rate` will behave the same way as before. If it is set, but `sample_rate` is not, then we subsample by volumes. I changed the default values for both of these arguments to None, in which case `1.0` will be used. Should be 100% backwards compatible.

2021-02-18 04:26 UTC, mmuckley approved these changes
Looks good to me! Great work!

2021-02-18 04:26 UTC, mmuckley commented on fastmri/data/mri_data.py
> +            )
:+1:

2021-02-18 04:26 UTC, mmuckley commented on fastmri/data/mri_data.py
> +            )
👍🏻

2021-02-18 04:26 UTC, mmuckley commented on fastmri/pl_modules/data_module.py
> +                volume_sample_rate = self.volume_sample_rate if i == 0 else None
Funny enough, I think this is unnecessary.

2021-02-18 04:27 UTC, merged