Filter function based on metadata for Datasets
facebookresearch/fastMRI pull request #257
Opened 2022-07-05 17:39 UTC by zaccharieramzi

This should close #256

2022-07-06 18:18 UTC, mmuckley requested changes
Overall this looks good to me. The only thing is I'm wondering if we can tweak the API for the examples list. I made a suggestion based on named tuples that would allow strong typing for any example filter. Might also want to rename `self.examples` to something more meaningful like `self.samples`. If you're using an editor like PyCharm or VS Code you should be able to refactor the name without having to crawl through all the code.

Would you be willing to add that to this PR?

2022-07-07 08:44 UTC, zaccharieramzi commented
@mmuckley Yes ofc always happy to help.

I am just wondering whether I should also apply the `example` -> `sample` change to the `banding_removal` subfolder? It has a lot of duplicated code atm, so not sure it's in a steady state anyway, no?

Also, I though that `raw_sample` was a bit more speaking than `sample`, because it allowed to make the difference with the sample classes defined in `transforms.py`. WDYT?

2022-07-07 09:22 UTC, zaccharieramzi commented on fastmri/data/mri_data.py
> +                    if self.example_filter(metadata)
All done, let me know what you think

2022-07-07 09:23 UTC, zaccharieramzi commented on tests/create_temp_data.py
> +                metadata[str(fname)] = (metadata_dict, num_slices)
thanks !

2022-07-08 21:41 UTC, mmuckley approved these changes
This looks great to me and seems to be passing all tests.

Since this is an API change it could break a few things - I'm going to go a head and merge into `main` for now and closely monitor for issues - may require a follow-up PR.

Great work @zaccharieramzi!

2022-07-08 21:41 UTC, merged