add feature varnet
facebookresearch/fastMRI pull request #340
Opened 2024-05-23 14:02 UTC by GiannakopoulosIlias

Added a new folder in fastmri_examples which includes the new modules for feature varent and ablations.
Added a new model file (feature_varnet) in fastmri/models which includes the new models.
Updated markdowns to include the new reference.

2024-06-12 16:59 UTC, mmuckley requested changes
Mostly asking for small reformatting items.

2024-06-12 16:59 UTC, mmuckley commented on fastmri/models/feature_varnet.py
> +from typing import NamedTuple, Optional, Tuple, List
Need the copyright header here - see other files in repo.

2024-06-12 16:59 UTC, mmuckley commented on fastmri_examples/feature_varnet/pl_modules/feature_varnet_module.py
> +import math
Add copyright header.

2024-06-12 16:59 UTC, mmuckley commented on fastmri_examples/feature_varnet/train_feature_varnet.py
> +import os
Add copyright header.

2024-06-12 16:59 UTC, mmuckley commented on fastmri_examples/feature_varnet/pl_modules/__init__.py
> +
This folder should have a different name and potentially gives a namespace conflict. Could you move `feature_varnet_module.py` to the top level and remove this folder? Then in `train_feature_varnet.py` import the module from `feature_varnet_module.py`.

2024-06-12 17:01 UTC, mmuckley commented
Also @GiannakopoulosIlias it looks like the PR is failing some linter tests. Could you also fix those?

2024-06-18 22:08 UTC, mmuckley commented
@GiannakopoulosIlias some tests still aren't passing. Please make sure you're using the correct version of `black` on your code.

2024-06-18 22:29 UTC, mmuckley commented
@GiannakopoulosIlias the message about Jupyter can be ignored. You only need to `pip install black` with the right version listed in the message.

2024-06-19 15:33 UTC, GiannakopoulosIlias commented
> @GiannakopoulosIlias the message about Jupyter can be ignored. You only need to `pip install black` with the right version listed in the message.

Should be okay now, thanks!

2024-06-19 21:40 UTC, mmuckley commented
Hello @GiannakopoulosIlias, now it looks like there are errors with type annotations with mypy.

If there are too many to deal with, you could move `feature_varnet.py` into the examples folder. Then you should be able to commit the code without fixing everything.

2024-06-19 22:17 UTC, GiannakopoulosIlias commented
> Hello @GiannakopoulosIlias, now it looks like there are errors with type annotations with mypy.
> 
> If there are too many to deal with, you could move `feature_varnet.py` into the examples folder. Then you should be able to commit the code without fixing everything.

I will try to adjust them tomorrow. They look many but I think most of them are the same error for all different model ablations.

2024-07-23 15:42 UTC, mmuckley approved these changes
Approving with fixes for moving the `feature_varnet.py` to `fastmri_examples`.

2024-07-23 15:42 UTC, merged